# Generated by Django 3.2.9 on 2021-11-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210418_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rent_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_date',
        ),
    ]
